<?php
/**
 * Auto generated by prado-cli.php on 2008-04-02 08:06:14.
 */
class AllowRecord extends TActiveRecord
{
	const TABLE='tbm_allowed';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>