<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class AsistenLuarRecord extends TActiveRecord
{
	const TABLE= 'tbd_asisten_luar';

	public $id;
	public $nama;
	public $alamat;
	public $telpon;
	public $keterangan;
	public $st_kelompok;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>