<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 09:57:05.
 */
class AskepRecord extends TActiveRecord
{
	const TABLE='tbm_askep';

	public $id;
	public $nama;
	public $kelas;
	public $tarif;
	public $st_persentase_kenaikan;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
