<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class AssetPenerimaanRecord extends TActiveRecord
{
	const TABLE='tbt_asset_penerimaan_brg';

	public $id;
	public $id_brg;	
	public $no_seri;
	public $garansi;	
	public $no_fak;
	public $tgl_fak;
	public $tgl_terima;
	public $tgl_jatuh_tempo;
	public $distributor;
	public $jml;		
	public $tgl;
	public $wkt;
	public $operator;
	public $ket;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>