<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class AssetFotoBrgRecord extends TActiveRecord
{
	const TABLE='tbm_asset_foto_barang';

	public $id;
	public $id_brg;
	public $kelompok;
	public $nama_file;
	public $foto;
	public $tipe;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>