<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class AssetBarangRecord extends TActiveRecord
{
	const TABLE='tbm_asset_barang';

	public $id;
	public $nama;
	public $prod;
	public $dist;
	public $penyusutan;
	public $ket;
	public $st_kel_habis_pakai;
	public $st_sub_kel_habis_pakai;
	public $st_bergerak;
	public $st_sub_bergerak;
	public $st_medis;
	public $st_elektrik;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>