<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class AssetKelHbsPakaiRecord extends TActiveRecord
{
	const TABLE='tbm_asset_kel_hbs_pakai';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>