<?php
/**
 * Auto generated by prado-cli.php on 2008-08-24 09:56:29.
 */
class AssetFotoBarangRecord extends TActiveRecord
{
	const TABLE='tbm_asset_foto_barang';

	public $id;
	public $id_brg;
	public $nama_file;
	public $foto;
	public $tipe;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>