<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:19:06.
 */
class BangunanRecord extends TActiveRecord
{
	const TABLE='tbd_asset_bangunan';

	public $id;
	public $alamat;
	public $luas;
	public $jml_lantai;
	public $nilai;
	public $tgl_bangun;
	public $no_surat;
	public $tgl_surat;
	public $notaris;
	public $ket;
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>