<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BayarPbfRecord extends TActiveRecord
{
	const TABLE='tbt_bayar_pbf';

	public $id;
	public $no_trans;
	public $no_po;
	public $no_faktur;
	public $total;
	public $tgl_bayar;
	public $petugas;
	public $tgl;
	public $wkt;
	public $st_tunda;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>