<?php
/**
 * Auto generated by prado-cli.php on 2008-05-17 10:58:33.
 */
class BayarRwtJlnRecord extends TActiveRecord
{
	const TABLE='tbt_bayar_rawat_jalan';

	public $no_trans;
	public $tindakan;
	public $total;
	public $bayar;
	public $sisa;
	public $operator;
	public $catatan;
	public $flag;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>