<?php
/**
 * Auto generated by prado-cli.php on 2008-05-23 06:21:35.
 */
class BbkObatRecord extends TActiveRecord
{
	const TABLE='tbt_bbk_barang';

	public $id;
	public $no_bbk;
	public $kode_obat;
	public $jumlah;
	public $tgl;
	
	public $id_petugas;
	public $id_penerima;
	
	public $petugas;
	public $penerima;
	public $sumber;
	public $tujuan;
	public $asal_dari;
	public $keterangan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>