<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:26.
 */
class BhpTindakanRecord extends TActiveRecord
{
	const TABLE='tbm_bhp_tindakan';

	public $id;
	public $nama;
	public $tarif;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>