<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 09:57:05.
 */
class BhpUnitRecord extends TActiveRecord
{
	const TABLE='tbm_bhp_unit';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
