<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:12:10.
 */
class BidanPerujukRecord extends TActiveRecord
{
	const TABLE='tbm_bidan_rujuk';

	public $id;
	public $nama;
	public $alamat;	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>