<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 07:46:31.
 */
class BulanRecord extends TActiveRecord
{
	const TABLE='tbm_bulan';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>