<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class CaraBayarRecord extends TActiveRecord
{
	const TABLE='tbm_carabayar';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>