<?php
/**
 * Auto generated by prado-cli.php on 2008-04-16 11:00:09.
 */
class caramasukRecord extends TActiveRecord
{
	const TABLE='tbm_cara_masuk';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>