<?php
/**
 * Auto generated by prado-cli.php on 2008-05-20 03:51:43.
 */
class ChangedRwtJlnRecord extends TActiveRecord
{
	const TABLE='tbt_rwtjln_changed';
	
	public $id;	
	public $no_trans_rwtjln;	
	public $dktr_awal;
	public $dktr_akhir;
	public $klinik_awal;
	public $klinik_akhir;
	public $operator;
	public $tgl;
	public $wkt;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>