<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ClaimAsuransiRecord extends TActiveRecord
{
	const TABLE='tbt_claim_asuransi';

	public $id;
	public $no_trans;
	public $tipe_rawat;
	public $no_trans_rawat;
	public $cm;
	public $penjamin;
	public $perus_asuransi;
	public $total;
	public $petugas;
	public $tgl;
	public $wkt;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>