<?php
/**
 * Auto generated by prado-cli.php on 2008-05-29 10:22:24.
 */
class CtScanJualLainRecord extends TActiveRecord
{
	const TABLE='tbt_ctscan_penjualan_lain';

	public $id;
	public $nama;
	public $no_trans;
	public $no_trans_pas_luar;
	public $no_reg;
	public $id_tindakan;
	public $tgl;
	public $film_size;
	public $jml_film;
	public $wkt;
	public $harga;
	public $harga_non_adm;
	public $harga_adm;
	public $disc;
	public $tanggungan_asuransi;
	public $operator;
	public $dokter_ctscan;
	public $flag;
	public $catatan;
	public $st_karyawan;
	public $st_rujukan;
	public $id_ctscan_rujukan;
	public $operator_kasir;
	public $no_trans_rwtjln_lain;
	public $st_ambil;
	public $st_cetak_hasil;
	
	public $operator_ambil;
	public $tgl_ambil;
	public $wkt_ambil;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>