<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 02:38:06.
 */
class CtScanKategRecord extends TActiveRecord
{
	const TABLE='tbm_ctscan_kategori';

	public $kode;
	public $jenis;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>