<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 03:40:15.
 */
class CtScanKelRecord extends TActiveRecord
{
	const TABLE='tbm_ctscan_kelompok';

	public $kode;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>