<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:14:21.
 */
class DerivatObatRecord extends TActiveRecord
{
	const TABLE='tbm_derivat_obat';

	public $id;
	public $nama;
	public $gol_id;
	public $klas_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>