<?php
/**
 * Auto generated by prado-cli.php on 2008-05-27 03:46:13.
 */
class DesFarmasiRecord extends TActiveRecord
{
	const TABLE='tbm_destinasi_farmasi';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>