<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:26.
 */
class EfisiensiBedRecord extends TActiveRecord
{
	const TABLE='tbt_efisiensi_bed';

	public $id;
	public $tahun;
	
	public $bor;
	public $alos;
	public $toi;
	public $bto;
	public $gdr;
	public $ndr;
	
	public $bor_target;
	public $alos_target;
	public $toi_target;
	public $bto_target;
	public $gdr_target;
	public $ndr_target;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>