<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class FilmRecord extends TActiveRecord
{
	const TABLE='tbm_film';

	public $id;
	public $nama;
	public $id_jenis_barang;
	public $jumlah;
	public $jml_satuan_besar;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>