<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 12:33:02.
 */
class FisioTdkRecord extends TActiveRecord
{
	const TABLE='tbm_fisio_tindakan';

	public $kode;
	public $nama;
	public $kategori;
	public $status;
	public $kelompok;
	public $normal;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>