<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 09:57:05.
 */
class FisioHasilRecord extends TActiveRecord
{
	const TABLE='tbt_fisio_hasil';

	public $cm;
	public $no_trans;
	public $tgl;
	public $wkt;
	public $id_fisio;
	public $hasil;
	public $operator;
	public $flag;
	public $id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>