<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:13:19.
 */
class GolObatRecord extends TActiveRecord
{
	const TABLE='tbm_golongan_obat';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>