<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:53:45.
 */
class HapusRecord extends TActiveRecord
{
	const TABLE='tbd_asset_hapus';

	public $no_trans;
	public $id_asset;
	public $petugas;
	public $bagian;
	public $tgl_hapus;
	public $alasan;
	public $ket;
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>