<?php
/**
 * Auto generated by prado-cli.php on 2008-05-29 06:37:41.
 */
class HrgFilmRecord extends TActiveRecord
{
	const TABLE='tbt_film_harga';

	public $id;
	public $kode;
	public $sumber;
	public $hrg_netto;
	public $hrg_ppn;
	public $hrg_netto_disc;
	public $hrg_ppn_disc;
	public $disc;
	public $tgl;
	public $st_pembelian;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>