<?php
/**
 * Auto generated by prado-cli.php on 2008-05-29 06:37:41.
 */
class HrgObatKhususRecord extends TActiveRecord
{
	const TABLE='tbm_obat_hrg_khusus';

	public $id;
	public $id_obat;
	public $hrg_jual;
	public $tgl;
	public $operator;
	public $ket;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>