<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:16:58.
 */
class IcdRecord extends TActiveRecord
{
	const TABLE='tbm_icd';

	public $dtd;
	public $kat;
	public $kode;
	public $inggris;
	public $indonesia;
	public $count;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>