<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 06:07:08.
 */
class IgdCaraMskRecord extends TActiveRecord
{
	const TABLE='tbt_igd_caramsk';

	public $no_trans;
	public $keterangan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>