<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ImunisasiRecord extends TActiveRecord
{
	const TABLE='tbm_imunisasi';

	public $id;
	public $nama;
	public $harga;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>