<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class InapKamarRecord extends TActiveRecord
{
	const TABLE='tbt_inap_kamar';

	public $id;
	public $cm;
	public $no_trans_inap;
	public $tgl_awal;
	public $wkt_masuk;
	public $id_kmr_awal;
	public $tgl_kmr_ubah;
	public $wkt_rubah;
	public $id_kmr_ubah;
	public $tgl_keluar;
	public $wkt_keluar;
	public $lama_inap;
	public $st_bayar;
	public $id_kmr_skrg;
	public $disc;
	public $tanggungan_asuransi;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
