<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class InapKhususRecord extends TActiveRecord
{
	const TABLE='tbt_inap_khusus';

	public $id;
	public $cm;
	public $no_trans_inap;
	public $no_trans_jln;
	public $tgl;
	public $wkt;
	public $operator;
	public $flag;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>