<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 02:02:35.
 */
class InapKamarBayiRecord extends TActiveRecord
{
	const TABLE='tbt_inap_kamar_bayi';

	public $id;
	public $cm;
	public $no_trans_inap;
	public $id_kamar;
	public $nama_kamar;
	public $lama_inap;
	public $tarif;
	public $disc;
	public $tanggungan_asuransi;
	public $tgl;
	public $wkt;
	public $operator;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>