<?php
/**
 * Auto generated by prado-cli.php on 2008-09-19 03:21:53.
 */
class InapBayarTunai extends TActiveRecord
{
	const TABLE='tbt_inap_bayar_tunai';

	public $id;
	public $no_trans_inap;
	public $no_reg_obat;
	public $disc_obat_tunai;
	public $tanggungan_asuransi_obat_tunai;
	public $jml_kurang_bayar;
	public $st_lunas_tunai;	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
