<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class InapSinarSisaRecord extends TActiveRecord
{
	const TABLE='tbt_inap_sinar_sisa';

	public $id;
	public $no_trans;
	public $tgl;	
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
