<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 07:46:31.
 */
class InapTdkMedisRecord extends TActiveRecord
{
	const TABLE='tbt_inap_tdk_medis';

	public $id;
	public $no_trans;
	public $wkt;
	public $tgl;
	public $cm;
	public $medis;
	public $id_tdk;
	public $operator;
	public $catatan;
	
	public $tarif;
	public $disc;
	public $tanggungan_asuransi;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>