<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class InapOperasiSisaPlafonRecord extends TActiveRecord
{
	const TABLE='tbt_inap_operasi_sisa_plafon';

	public $id;
	public $cm;
	public $no_trans_inap;	
	public $tgl;
	public $obat;
	public $lab;
	public $rad;
	public $fisio;
	public $kamar;
	public $jpm;
	public $visite;
	public $total;
	public $operator;
	public $flag;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
