<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class InapAdmRecord extends TActiveRecord
{
	const TABLE='tbt_inap_adm';

	public $id;
	public $no_trans;
	public $cm;
	public $tgl;
	public $wkt;
	public $tarif_adm;
	public $tarif_rujukan;
	public $total_tarif;
	public $operator;
	public $flag;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>