<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class InapBhpRecord extends TActiveRecord
{
	const TABLE='tbt_inap_bhp';

	public $id;
	public $cm;
	public $no_trans;
	public $id_kateg;
	public $id_tdk;
	public $tgl;
	public $wkt;
	public $operator;
	public $flag;
	public $tarif;
	public $catatan;


	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
