<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class InapSinarRecord extends TActiveRecord
{
	const TABLE='tbt_inap_sinar';

	public $id;
	public $cm;
	public $no_trans;	
	public $tgl;
	public $wkt;
	public $operator;
	public $flag;
	public $catatan;
	public $tarif;
	
	public $disc;
	public $tanggungan_asuransi;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
