<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:11:30.
 */
class JasaResepRacikanRecord extends TActiveRecord
{
	const TABLE='tbm_jasa_resep_racikan';

	public $id;
	public $jasa_resep;
	public $jasa_racikan;
	public $bungkus;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>