<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:16:00.
 */
class JenisAssetRecord extends TActiveRecord
{
	const TABLE='tbm_jenis_asset';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>