<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class JenisRawatRecord extends TActiveRecord
{
	const TABLE='tbm_jenis_rawat';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>