<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 01:54:36.
 */
class JpmHargaRecord extends TActiveRecord
{
	const TABLE='tbm_jpm_harga';
	
	public $id	;
	public $id_person;
	public $id_kls;
	public $tarif;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>