<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:58:36.
 */
class KabRecord extends TActiveRecord
{
	const TABLE='tbm_kabupaten';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>