<?php
/**
 * Auto generated by prado-cli.php on 2008-04-02 07:33:35.
 */
class KabupatenRecord extends TActiveRecord
{
	const TABLE='tbm_kabupaten';

	public $id;
	public $id_propinsi;
	public $id_prop_tmp;
	public $nama;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>