<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:03:05.
 */
class KamarOperasiNamaRecord extends TActiveRecord
{
	const TABLE='tbm_operasi_kamar_nama';

	public $id;
	public $nama;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>