<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:03:23.
 */
class KamarOperasiTarifRecord extends TActiveRecord
{
	const TABLE='tbm_operasi_kamar_tarif';

	public $id;	
	public $id_kamar_operasi;
	public $id_kategori_operasi;
	public $id_kelas;
	public $tarif;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>