<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 01:54:36.
 */
class KamarHargaRskbRecord extends TActiveRecord
{
	const TABLE='tbm_kamar_harga_rskb';
	
	public $id	;
	public $kelas;
	public $kel_dokter;
	public $tarif;
	public $viste;
	public $adm;
	public $jpm;
	public $jsp;
	public $uk;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
