<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:12:10.
 */
class KasirPendaftaranRecord extends TActiveRecord
{
	const TABLE='tbt_kasir_pendaftaran';

	public $id;
	public $no_trans;
	public $no_trans_pdftr;
	public $no_karcis;
	public $klinik;
	public $dokter;
	public $id_tindakan;
	public $tgl;
	public $waktu;
	public $operator;
	public $tarif;
	public $st_flag;
	
	public $operator_kasir;
	public $tgl_kasir;
	public $wkt_kasir;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>