<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class KasirRwtJlnAngsuranRecord extends TActiveRecord
{
	const TABLE='tbt_kasir_rwtjln_angsuran';

	public $id;
	public $tipe_pasien;
	public $cm;
	public $no_trans;
	public $no_trans_asal;
	public $tgl;
	public $waktu;
	public $operator;
	public $tarif;
	public $no_ref;
	public $st_carabayar;
	public $st;
	public $cara_bayar_ke;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>