<?php
/**
 * Auto generated by prado-cli.php on 2008-05-21 11:01:38.
 */
class KasirIgdRecord extends TActiveRecord
{
	const TABLE='tbt_kasir_igd';

	public $no_trans;
	public $id_tindakan;
	public $tgl;
	public $waktu;
	public $operator;
	public $bhp;
	public $tarif;
	public $total;
	public $st_flag;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>