<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:58:54.
 */
class KecRecord extends TActiveRecord
{
	const TABLE='tbm_kecamatan';

	public $id_kab;
	public $id;
	public $nama;
	public $nama_kab;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>