<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 12:35:29.
 */
class KelasKamarRecord extends TActiveRecord
{
	const TABLE='tbm_kamar_kelas';

	public $id;
	public $nama;
	public $persentase;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>