<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:59:34.
 */
class KelompokRecord extends TActiveRecord
{
	const TABLE='tbm_kelompok';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>