<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 12:36:27.
 */
class KelompokPegawaiRecord extends TActiveRecord
{
	const TABLE='tbm_pegawai_kelompok';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>