<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:59:10.
 */
class KelRecord extends TActiveRecord
{
	const TABLE='tbm_kelurahan';

	public $id_kab;
	public $id_kec;
	public $id;
	public $id_pk;
	public $nama;
	public $nama_kec;
	public $nama_kab;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>