<?php
/**
 * Auto generated by prado-cli.php on 2008-04-02 07:33:35.
 */
class KelurahanRecord extends TActiveRecord
{
	const TABLE='tbm_kelurahan';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>