<?php
/**
 * Auto generated by prado-cli.php on 2008-05-23 06:21:35.
 */
class KemasanRecord extends TActiveRecord
{
	const TABLE='tbm_kemasan';

	public $id;
	public $nama;
	public $hrg;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>