<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:13:58.
 */
class KlasifikasiObatRecord extends TActiveRecord
{
	const TABLE='tbm_klasifikasi_obat';

	public $id;
	public $jenis;
	public $gol_id;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>