<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class KomisiTransRecord extends TActiveRecord
{
	const TABLE='tbt_komisi_trans';

	public $id;
        public $id_dokter_perujuk_dalam;
        public $id_bidan_perujuk;
	public $nama;
	public $tgl;
	public $wkt;
	public $komisi;
	public $st_rawat;
	public $no_trans_rwt_jln;
	public $no_trans_rwt_inap;
	public $st_dibyr;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>