<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 09:57:05.
 */
class LabHasilRecord extends TActiveRecord
{
	const TABLE='tbt_lab_hasil';

	public $cm;
	public $no_trans;
	public $tgl;
	public $wkt;
	public $id_lab;
	public $id_paket;
	public $kode_item_paket;
	public $hasil;
	public $nilai_normal_pria;
	public $nilai_normal_wanita;
	public $operator;
	public $flag;
	public $id;
	public $st_cetak;
	public $tipe_pasien;
	
	public $operator_ambil;
	public $tgl_ambil;
	public $wkt_ambil;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
