<?php
/**
 * Auto generated by prado-cli.php on 2008-05-29 09:26:51.
 */
class LabJualRecord extends TActiveRecord
{
	const TABLE='tbt_lab_penjualan';

	public $id;
	public $cm;
	public $no_trans;
	public $no_trans_rwtjln;
	public $no_reg;
	public $id_tindakan;
	public $tgl;
	public $wkt;
	public $harga;
	public $disc;
	public $tanggungan_asuransi;
	public $operator;
	public $flag;
	public $dokter;
	public $klinik;
	public $st_rujukan;
	public $id_lab_rujukan;
	public $catatan;
	
	public $st_cetak_hasil;
	public $st_ambil;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>