<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 12:33:20.
 */
class LabKategRecord extends TActiveRecord
{
	const TABLE='tbm_lab_kategori';

	public $kode;
	public $jenis;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>