<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 10:00:12.
 */
class LabPaketRecord extends TActiveRecord
{
	const TABLE='tbm_lab_paket';

	public $id;
	public $id_paket;
	public $kode;
	public $item;
	public $normal;
	public $normal_perempuan;
	public $st_rujukan;
	public $kategori;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>