<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 12:34:46.
 */
class LabRujukanRecord extends TActiveRecord
{
	const TABLE='tbm_lab_rujukan';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>