<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 12:33:02.
 */
class LabTdkRecord extends TActiveRecord
{
	const TABLE='tbm_lab_tindakan';

	public $kode;
	public $nama;
	public $kategori;
	public $status;
	public $kelompok;
	public $normal;
	public $normal_perempuan;
	public $st_paket;
	public $st_rujukan;
	public $id_lab_rujukan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>