<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 01:35:11.
 */
class LuarkotaRecord extends TActiveRecord
{
	const TABLE='tbd_luarkota';

	public $cm;
	public $id_kab;
	public $kecamatan;
	public $kelurahan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>