<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:39:39.
 */
class MutasiRecord extends TActiveRecord
{
	const TABLE='tbd_asset_mutasi';

	public $no_trans;
	public $id_asset;
	public $tgl_mutasi;
	public $petugas;
	public $bagian;
	public $penerima;
	public $tgl_terima;
	public $ket;
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>