<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:26.
 */
class NamaTindakanPaketRecord extends TActiveRecord
{
	const TABLE='tbm_nama_tindakan_paket';

	public $id;
	public $nama;
	public $tarif;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>