<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:26.
 */
class NamaTindakanPaketDetailRecord extends TActiveRecord
{
	const TABLE='tbm_nama_tindakan_paket_detail';

	public $id;
	public $id_paket;
	public $id_tindakan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>