<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:26.
 */
class NamaTindakanRecord extends TActiveRecord
{
	const TABLE='tbm_nama_tindakan';

	public $id;
	public $id_klinik;
	public $nama;
	public $total;
	public $st_rawat;
	public $st_paket;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>