<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class ObatPaketKelompokRecord extends TActiveRecord
{
	const TABLE='tbm_obat_paket_kelompok';

	public $id;
	public $nama;
	public $st;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
