<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class ObatReturJalanRecord extends TActiveRecord
{
	const TABLE='tbt_obat_retur_jalan';

	public $no_trans;
	public $no_trans_rwtjln;
	public $no_reg;
	public $cm;
	public $dokter;
	public $klinik;
	public $tgl;
	public $wkt;
	public $operator;
	public $sumber;
	public $tujuan;
	public $id_obat;
	public $id_harga;
	public $expired;
	public $jumlah_awal;
	public $jumlah;
	public $hrg;
	public $total;
	public $flag;
	public $alasan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>