<?php
/**
 * Auto generated by prado-cli.php on 2008-09-19 03:21:53.
 */
class ObatJualInapRecord extends TActiveRecord
{
	const TABLE='tbt_obat_jual_inap';

	public $id;
	public $no_trans;
	public $no_trans_inap;
	public $no_reg;
	public $cm;
	public $dokter;	
	public $tgl;
	public $wkt;
	public $operator;
	public $sumber;
	public $tujuan;
	public $id_obat;
        public $keterangan_obat;
        public $id_trans_pengganti;
	public $id_harga;
	public $jumlah;
	public $hrg_nett;
	public $hrg_ppn;
	public $hrg_nett_disc;
	public $hrg_ppn_disc;
	public $hrg;
	public $total;
	public $total_real;
	public $flag;
        public $flag_ambil_resep;
        public $flag_salinan_resep;
	public $st_bayar;
	public $st_obat_khusus;
	public $st_racik;
	public $id_kel_racik;
	public $r_item;
	public $r_racik;
	public $bungkus_racik;
	public $id_kemasan;	
	
	public $st_imunisasi;
	public $id_kel_imunisasi;
	
	public $operator_kasir;
	
	public $id_bhp;
	public $bhp;
	
	public $st_lunas_tunai;
	public $expired;
	public $persentase_dokter;
	
	public $st_paket;
	public $id_kel_paket;
	public $jml_paket;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
