<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class ObatPaketRecord extends TActiveRecord
{
	const TABLE='tbm_obat_paket';

	public $id;
	public $id_kelompok_paket;
	public $id_obat;
	public $jumlah;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
