<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class ObatJualPoliRecord extends TActiveRecord
{
	const TABLE='tbt_obat_jual_poli';

	public $id;
	public $no_reg;
	public $tgl;
	public $wkt;
	public $operator;
	public $sumber;
	public $tujuan;
	public $id_obat;
	public $id_harga;
	public $jumlah;
	public $hrg_nett;
	public $hrg_ppn;
	public $hrg_nett_disc;
	public $hrg_ppn_disc;
	public $hrg;
	public $total;
	public $total_real;
	public $flag;
	public $st_obat_khusus;
	public $st_racik;
	public $id_kel_racik;
	public $r_item;
	public $r_racik;
	public $bungkus_racik;
	public $id_kemasan;	
	public $st_imunisasi;
	public $id_kel_imunisasi;	
	public $operator_kasir;
	
	public $id_bhp;
	public $bhp;
	
	public $expired;
	public $persentase_dokter;
	
	public $st_paket;
	public $id_kel_paket;
	public $jml_paket;
	public $st_costsharing;
	public $st_ffs;
	public $ket;
	
	public $st_delete;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
