<?php
/**
 * Auto generated by prado-cli.php on 2008-09-19 03:21:53.
 */
class ObatJualInapReturRecord extends TActiveRecord
{
	const TABLE='tbt_obat_jual_inap_retur';

	public $no_trans;
	public $no_trans_inap;
	public $cm;
	public $dokter;	
	public $tgl;
	public $wkt;
	public $operator;
	public $sumber;
	public $tujuan;
	public $id_obat;
	public $jumlah_awal;
	public $jumlah;
	public $hrg;
	public $total;
	public $flag;
	public $alasan;
	
	public $no_reg;
	public $id_harga;
	public $expired;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>