<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:16:22.
 */
class ObatJenisRecord extends TActiveRecord
{
	const TABLE='tbm_obat_jenis';

	public $id;
	public $nama;
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>