<?php
/**
 * Auto generated by prado-cli.php on 2008-05-30 03:30:34.
 */
class ObatJualTundaRecord extends TActiveRecord
{
	const TABLE='tbt_obat_jual_tunda';

	public $id;
	public $jns_pasien;
	public $no_trans_rawat;
	public $nama;
	public $cm;
	public $dokter;
	public $klinik;
	public $id_obat;
	public $jumlah;
	public $hrg_nett;
	public $hrg_ppn;
	public $hrg_nett_disc;
	public $hrg_ppn_disc;
	public $hrg;
	public $hrg_bulat;
	public $total;
	public $total_real;
	public $id_kel_racik;
	public $r_item;
	public $r_racik;
	public $bungkus_racik;
	public $id_kemasan;
	public $tujuan;
	public $id_harga;
	public $st_obat_khusus;
	public $st_racik;
	public $st_imunisasi;
	public $id_kel_imunisasi;
	
	public $st_bayar;
	public $expired;
	public $id_bhp;
	public $nama_bhp;
	public $bhp;	
	public $jml_tagihan;
	public $sumber;
	public $persentase_dokter;
	
	public $tipe_pasien_luar;
	
	public $ruangan;
	public $petugas_internal;	
	
	public $tgl;
	public $wkt;	
	public $operator;
	
	public $tgl_cetak;
	public $wkt_cetak;	
	public $operator_cetak;
	
	public $st;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
