<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class ObatBhpRecord extends TActiveRecord
{
	const TABLE='tbm_obat_bhp';

	public $id;
	public $nama;
	public $bhp;
        public $flag_input_dr;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>