<?php
/**
 * Auto generated by Kampre ~ ActiveRecordGen.php on 2009-06-17 07:30:52.
 */
class ObatRecord extends TActiveRecord
{
	const TABLE='tbm_obat';

	public $kode;
	public $nama;
	public $nama_generik;
        public $flag_input_dr;
	public $kel_obat;
	public $kel_margin;
	public $kel_standard;
	public $satuan;
	public $jml_satuan_besar;
	public $ket;
	public $gol;
	public $klasifikasi;
	public $derivat;
	public $produsen;
	public $pbf;
	public $kategori;
	public $tipe;
	public $jenis;
	public $persentase_dokter;
	public $st;
	public $min_2;
	public $tol_2;
	public $max_2;
	public $min_3;
	public $tol_3;
	public $max_3;
	public $min_4;
	public $tol_4;
	public $max_4;
	public $min_5;
	public $tol_5;
	public $max_5;
	public $min_6;
	public $tol_6;
	public $max_6;
	public $min_7;
	public $tol_7;
	public $max_7;
	public $min_8;
	public $tol_8;
	public $max_8;
	public $min_9;
	public $tol_9;
	public $max_9;
	public $min_10;
	public $tol_10;
	public $max_10;
	public $min_11;
	public $tol_11;
	public $max_11;
	public $min_12;
	public $tol_12;
	public $max_12;
	public $min_13;
	public $tol_13;
	public $max_13;
	public $min_14;
	public $tol_14;
	public $max_14;
	public $min_15;
	public $tol_15;
	public $max_15;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
