<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class ObatKelompokMarginRecord extends TActiveRecord
{
	const TABLE= 'tbm_obat_kelompok_margin';

	public $id;
	public $nama;
	public $persentase;
	public $persentase_asuransi;
	public $persentase_jamper;
	public $persentase_unit_internal;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>