<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:04:07.
 */
class OperasiKategoriRecord extends TActiveRecord
{
	const TABLE='tbm_operasi_kategori';
	
	public $id;	
	public $nama;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>