<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:04:07.
 */
class OperasiTarifRecord extends TActiveRecord
{
	const TABLE='tbm_operasi_tarif';
	
	public $id;	
	public $id_operasi;
	public $id_kelas;
		
	public $js_dok_obgyn;
	public $js_dok_anestesi;
	public $js_dok_anak;
	
	public $visit_dok_obgyn;
	public $visit_dok_anak;
	public $sewa_ok;
	public $obat;
	public $ctg;
	public $asisten;
	public $jpm;
	public $lab;
	public $ambulan;
	public $kamar_ibu;
	public $kamar_bayi;
	public $js_bidan_pengirim;
	
	public $adm;
	public $materai;
	public $lama_hari;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>