<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:07:22.
 */
class OperasiBillingRecord extends TActiveRecord
{
	const TABLE='tbt_inap_operasi_billing';

	public $id;
	public $cm;
	public $no_trans;
	public $id_opr;
	public $nm_opr;
	public $tgl;
	public $wkt;
	
	public $dktr_obgyn;
	public $tarif_obgyn;
	public $tarif_pengembang_obgyn;
	public $tarif_penyulit_obgyn;
	
	public $dktr_anastesi;
	public $tarif_anastesi;
	public $tarif_pengembang_anastesi;
	public $tarif_penyulit_anastesi;
	
	public $dktr_anak;
	public $tarif_anak;
	public $tarif_pengembang_anak;
	public $tarif_penyulit_anak;
	
	public $ass_dktr;
	public $tarif_assdktr;
	public $tarif_pengembang_assdktr;
	public $tarif_penyulit_assdktr;
	
	public $dktr_resusitasi;
	public $tarif_resusitasi;
	public $tarif_pengembang_resusitasi;
	public $tarif_penyulit_resusitasi;
	
	public $paramedis;
	public $tarif_paramedis;
	public $tarif_pengembang_paramedis;
	public $tarif_penyulit_paramedis;
	
	public $tarif_pengembang;
	public $tarif_penyulit;
	
	public $rs;
	
	public $jasa_koordinator;
	public $jasa_koordinator_anastesi;
	public $jasa_koordinator_ast_anastesi;
	public $jasa_koordinator_ast_instrumen;
	public $jasa_koordinator_paramedis;
	public $jasa_koordinator_resusitasi;
	
	public $visite_dokter_obgyn;
	public $visite_dokter_anak;
	public $sewa_ok;
	public $obat;
	public $ctg;
	public $jpm;
	public $lab;
	public $ambulan;
	public $kamar_ibu;
	public $kamar_bayi;
	public $js_bidan_pengirim;
	public $adm;
	public $materai;
	public $st;
	public $operator;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>