<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:03:48.
 */
class OperasiNamaRecord extends TActiveRecord
{
	const TABLE='tbm_operasi_nama';

	public $id;
	public $nama;
	public $id_kamar_operasi;
	public $id_kategori_operasi;
	public $st;
	public $st_operasi;
	
	public $index_operator;
	public $index_anastesi;
	public $index_ast_anastesi;
	public $index_ast_instrumen;
	public $index_paramedis;
	public $index_resusitasi;
	public $index_pengembang;
	public $index_penyulit;
	
	public $persentase_jasa_koordinator;
	public $persentase_jasa_koordinator_anastesi;
	public $persentase_jasa_koordinator_ast_anastesi;
	public $persentase_jasa_koordinator_ast_instrumen;
	public $persentase_jasa_koordinator_paramedis;
	public $persentase_jasa_koordinator_resusitasi;
	
	public $persentase_rs;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>