<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:07:22.
 */
class OperasiBillingLuarRecord extends TActiveRecord
{
	const TABLE='tbt_inap_operasi_billing_luar';

	public $id;
	public $cm;
	public $no_trans;
	public $id_opr;
	public $nm_opr;
	public $tgl;
	
	public $dktr_utama;
	public $tarif_dktr;
	public $st_byr_dktr;
	
	public $ass_dktr;
	public $tarif_assdktr;
	public $st_byr_assdktr;
	
	public $dktr_anastesi;
	public $tarif_anastesi;
	public $st_byr_anastesi;
	
	public $ass_anastesi;
	public $tarif_assanastesi;
	public $st_byr_assanastesi;
	
	public $dktr_anak;
	public $tarif_anak;
	public $st_byr_anak;
	
	public $dktr_obgyn;
	public $tarif_obgyn;
	public $st_byr_obgyn;
	
	public $ass_obgyn;
	public $tarif_assobgyn;
	public $st_byr_assobgyn;
	
	public $bidan;
	public $tarif_bidan;
	public $st_byr_bidan;
	
	public $ass_bidan;
	public $tarif_assbidan;
	public $st_byr_assbidan;
	
	public $petugas_resusitasi;
	public $tarif_petugas_resusitasi;
	public $st_byr_petugas_resusitasi;
	
	public $pm1;
	public $tarif_pm1;
	public $st_byr_pm1;
	
	public $pm2;
	public $tarif_pm2;
	public $st_byr_pm2;
	
	public $pm3;
	public $tarif_pm3;
	public $pm4;
	public $tarif_pm4;
	public $pm5;
	public $tarif_pm5;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>