<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:14:50.
 */
class PasienRecord extends TActiveRecord
{
	const TABLE='tbd_pasien';

	public $cm;
	public $nama;
	public $satuation;
	public $tmp_lahir;
	public $tgl_lahir;
	public $kelompok;
	public $id_keluarga;
	public $perusahaan;
	public $no_asuransi;
	public $kontrakID;
	public $status;
	public $agama;
	public $jkel;
	public $alamat;
	public $alamat_tdk_lengkap;
	public $no_rmh;
	public $rt;
	public $rw;
	public $propinsi;
	public $kabupaten;
	public $kecamatan;
	public $kelurahan;
	public $kabupaten_nama;
	public $kecamatan_nama;
	public $kelurahan_nama;
	public $telp;
	public $hp;
	public $suku;
	public $umur;
	public $goldar;
	public $wni;
	public $pekerjaan;
	public $pendidikan;
	public $catatan;
	
	public $nm_istri;
	public $nm_suami;
	public $nm_ayah;
	public $nm_ibu;
	public $nm_pj;
	public $hubungan_pj;
	public $alamat_pj;
	public $telp_pj;
	public $hp_pj;
	public $st_cetak_kartupasien;
	public $st_baru_lama;
	
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
