<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class PasienLuarRecord extends TActiveRecord
{
	const TABLE= 'tbd_pasien_luar';

	public $no_trans;
	public $cm;
	public $nama;
	public $alamat;
	public $umur;
	public $jkel;
	public $id_pas_luar_karyawan;
	public $st_kepegawaian;
	public $st_piutang;
	
	public $disc_obat;
	public $tanggungan_asuransi_obat;
	public $alasan_tunda;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>