<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 02:02:35.
 */
class PegawaiRecord extends TActiveRecord
{
	const TABLE='tbd_pegawai';

	public $id;
	public $nama;
	public $jkel;
	public $tmp_lahir;
	public $tgl_lahir;
	public $st_kawin;
	public $agama;
	public $kelompok;
	public $status;
	public $jabatan;
	public $spesialis;
	public $poliklinik;
	public $nip;
	
	public $no_rek;
	public $npwp;
	public $sip;
	
	public $alamat;
	public $rt;
	public $rw;
	public $kabupaten;
	public $kecamatan;
	public $kelurahan;
	public $telepon;
	public $no_hp;
	public $pendidikan;
	public $kec_luar;
	public $kel_luar;
	public $catatan;
	public $st_sub_spesialis;
	public $st_tarif_khusus_operasi;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>