<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:00:40.
 */
class PekerjaanRecord extends TActiveRecord
{
	const TABLE='tbm_pekerjaan';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>