<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:16:00.
 */
class PengadaanAssetRecord extends TActiveRecord
{
	const TABLE='tbd_asset_pengadaan';

	public $id;
	public $no_po;
	public $tgl_beli;
	public $petugas;
	public $jenis;
	public $nama;
	public $jumlah;
	public $harga;
	public $total;
	public $penyusutan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>