<?php
/**
 * Auto generated by prado-cli.php on 2008-09-18 02:03:48.
 */
class PengaliJasaKoordinatorRecord extends TActiveRecord
{
	const TABLE='tbm_pengali_jasa_koordinator';

	public $id;
	public $nilai;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>