<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:46:40.
 */
class PerawatanRecord extends TActiveRecord
{
	const TABLE='tbd_asset_perawatan';

	public $no_trans;
	public $id_asset;
	public $petugas;
	public $bagian;
	public $tgl_rawat;
	public $biaya;
	public $pelaksana;
	public $alamat;
	public $tlp;
	public $garansi;
	public $alasan;
	public $ket;
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>