<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:59:57.
 */
class PerusahaanRecord extends TActiveRecord
{
	const TABLE='tbm_perusahaan_asuransi';

	public $id_kel;
	public $id;
	public $nama;
	public $st;
	public $st_detail;
	public $plafon_master;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>