<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:14:46.
 */
class ProdusenObatRecord extends TActiveRecord
{
	const TABLE='tbm_produsen_obat';

	public $id;
	public $nama;
	public $alamat;
	public $tlp;
	public $status;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>