<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 11:59:57.
 */
class ProviderDetailObatRecord extends TActiveRecord
{
	const TABLE='tbm_provider_detail_obat';

	public $id;
	public $id_provider;
	public $id_poli;
	public $plafon;
	public $margin;
	public $disc;
	public $st;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>