<?php
/**
 * Auto generated by prado-cli.php on 2008-09-19 06:54:26.
 */
class RadJualInapRecord extends TActiveRecord
{
	const TABLE='tbt_rad_penjualan_inap';

	public $cm;
	public $no_trans;
	public $no_trans_inap;
	public $no_reg;
	public $id_tindakan;
	public $pengali;
	public $tgl;
	public $wkt;
	public $harga;
	public $disc;
	public $tanggungan_asuransi;
	public $operator;
	public $dokter;
	public $dokter_rad;
	public $catatan;
	public $film_size;
	public $jml_film;
	public $flag;
	public $st_ambil;
	public $st_cetak_hasil;
	public $st_bayar;
	public $id;
	
	public $st_rujukan;
	public $id_rad_rujukan;
	
	public $st_lunas_tunai;
	
	public $operator_ambil;
	public $tgl_ambil;
	public $wkt_ambil;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
