<?php
/**
 * Auto generated by prado-cli.php on 2008-05-28 11:07:29.
 */
class RadTarifRecord extends TActiveRecord
{
	const TABLE='tbm_rad_tarif';

	public $id;
	public $tarif;	
	public $tarif1;	
	public $tarif2;	
	public $tarif3;	
	public $tarif4;
	public $tarif5;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>