<?php
/**
 * Auto generated by prado-cli.php on 2008-05-24 02:37:48.
 */
class RadTdkRecord extends TActiveRecord
{
	const TABLE='tbm_rad_tindakan';

	public $kode;
	public $nama;
	public $kategori;
	public $kelompok;
	public $id;	
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>