<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 12:35:03.
 */
class RuangRecord extends TActiveRecord
{
	const TABLE='tbm_ruang';

	public $id;
	public $id_kelas;
	public $id_jns_kamar;	
	public $nama;
	public $jml_bed;
	public $jml_bed_pakai;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>