<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class RwtInapUangMukaRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_inap_uang_muka';
	
	public $no_trans;
	public $cm;
	public $no_trans_inap;
	public $tgl;
	public $wkt;
	public $jumlah;
	public $st;
	public $operator;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>