<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class RwtInapRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_inap';

	public $no_trans;
	public $tgl_masuk;
	public $wkt_masuk;
	public $kelas;
	public $kamar;
	public $jenis_kamar;
	public $bed;
	public $cm;
	public $tg_pembayaran;
	public $kategori;
	public $nama_pgg;
	public $alamat_pj;
	public $telp_pj;
	public $hp_pj;
	public $pekerjaan_pgg;
	public $hub_pasien;
	public $cr_masuk;
	public $dokter;
	public $diagnosa_masuk;
	public $diagnosa_keluar;
	public $icd;
	public $keluhan;
	public $catatan;
	public $status;
	public $tgl_keluar;
	public $jam_keluar;
	public $cr_keluar;
	public $keadaan_keluar;
	public $pembayaran;
	public $st_pulang;
	public $st_resume;
	public $st_rujukan;
	public $id_bidan_perujuk;
	public $id_dokter_perujuk_dalam;
	public $nm_perujuk;	
	public $lama_inap;
	public $st_alih;
	public $penjamin;
	public $perus_asuransi;
	public $st_asuransi;
	public $st_asuransi_byr;
	public $discount;
	public $dp;
	public $kasir;
	public $wkt_kasir;
	public $tgl_kasir;
	
	public $tipe_rujukan;
	
	public $st_carabayar;
	public $no_referensi;
	public $st_piutang;
	
	public $disc_obat;
	public $tanggungan_asuransi_obat;
	
	public $disc_obat_kredit;
	public $tanggungan_asuransi_obat_kredit;
	
	public $sisa_tagihan_pembayaran_tunai;
	public $nm_pembayar;
	public $st_bayi;
	public $alasan_tunda;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>