<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class RwtInapResumeRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_inap_resume';

	public $id;
	public $cm;
	public $tgl;
	public $wkt;
	public $operator;
	public $diagnosa_masuk;
	public $diagnosa_keluar;
	public $bedah;
	public $tdk_khusus;
	public $anjuran;
	public $dokter;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>