<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class RwtInapRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_inap';

	public $no_trans;
	public $tgl_masuk;
	public $wkt_masuk;
	public $kelas;
	public $kamar;
	public $jenis_kamar;
	public $cm;
	public $tg_pembayaran;
	public $kategori;
	public $nama_pgg;
	public $pekerjaan_pgg;
	public $jaminan;
	public $alamat;
	public $hub_pasien;
	public $cr_masuk;
	public $dokter;
	public $diagnosa_masuk;
	public $diagnosa_keluar;
	public $icd;
	public $catatan;
	public $status;
	public $tgl_keluar;
	public $jam_keluar;
	public $cr_keluar;
	public $keadaan_keluar;
	public $pembayaran;
	public $st_pulang;
	public $st_resume;
	public $st_rujukan;
	public $lama_inap;
	public $st_alih;
	public $discount;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>