<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class RwtInapPasPulangRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_inap_pulang';

	public $id;
	public $cm;
	public $mode;
	public $tgl_masuk;
	public $wkt_masuk;
	public $tgl_keluar;
	public $wkt_keluar;	
	public $cr_keluar;
	public $keadaan_keluar;
	public $pembayaran;	
	public $operator;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>