<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:12:10.
 */
class RwtjlnLainRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_jalan_lain';

	public $no_trans;
	public $nama;
	public $flag;	
	public $kasir;
	public $tgl;
	public $wkt;
	public $st_carabayar;
	public $no_referensi;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>