<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:12:10.
 */
class RwtjlnRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_jalan';

	public $cm;
	public $no_trans;
	public $no_karcis;
	public $id_klinik;	
	public $tgl_visit;
	public $wkt_visit;
	public $cr_masuk;
	public $dokter;
	public $keluhan;
	public $icd;
	public $catatan;
	public $flag;
	public $st_alih;
	public $penjamin;
	public $perus_asuransi;
	public $st_asuransi;
	public $st_asuransi_byr;
	public $st_rujuk;
	public $id_dokter_perujuk_dalam;
	public $id_bidan_perujuk;
	public $nm_perujuk;
	public $discount;
	public $penanggung_jawab;
	public $hubungan_pj;
	public $alamat_pj;
	public $telp_pj;
	public $hp_pj;
	public $kasir;
	public $wkt_kasir;
	public $tgl_kasir;
	public $st_tebus_luar;
	public $st_kredit;
	public $st_piutang;
	
	public $st_carabayar;
	public $no_referensi;
	
	public $disc_obat;
	public $tanggungan_asuransi_obat;
	public $shift;
	public $alasan_tunda;
	
	public $st_ambil_kartu;
	public $st_pdftr;
	public $st_dokter_poli_lain;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>