<?php
/**
 * Auto generated by prado-cli.php on 2008-04-02 08:06:14.
 */
class RwtJlnAskesRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_jalan_askes';

	public $no_trans_rwtjln;
	public $tgl;
	public $wkt;
	public $no_sjp;
	public $operator;
	public $st_claim;
	public $st_bayar;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
