<?php
/**
 * Auto generated by prado-cli.php on 2008-04-27 05:13:02.
 */
class SatuanObatRecord extends TActiveRecord
{
	const TABLE='tbm_satuan_obat';

	public $kode;
	public $nama;
	public $tipe;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>