<?php
/**
 * Auto generated by prado-cli.php on 2008-05-07 11:45:06.
 */
class SimpegRecord extends TActiveRecord
{
	const TABLE='tbd_simpeg';

	public $nip;
	public $nama;
	public $jns_kelamin;
	public $tmp_lahir;
	public $tgl_lahir;
	public $agama;
	public $status_kawin;
	public $jns_pasangan;
	public $nm_pasangan;
	public $tmp_lahir_pasangan;
	public $tgl_lahir_pasangan;
	public $tgl_kawin;
	public $no_kartu_kawin;
	public $tmt_jd_peg;
	public $pendidikan;
	public $status_kepeg;
	public $jns_kepeg;
	public $no_karpeg;
	public $gol_akhir;
	public $tmt;
	public $no_sk_penempatan;
	public $tgl_tgs_unit;
	public $nm_unit;
	public $nm_satgas;
	public $kab_kota;
	public $prop;
	public $nm_jabatan;
	public $tgl_mulai;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>