<?php
/**
 * Auto generated by prado-cli.php on 2008-05-08 02:37:30.
 */
class SimpegPendidikanRecord extends TActiveRecord
{
	const TABLE='tbd_simpeg_pendidikan';

	public $id;
	public $nip;
	public $nm_pendidikan;
	public $thn_lulus;
	public $jur_pendidikan;
	public $instansi_pendidikan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>