<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 12:02:28.
 */
class SimpanCaraMskRecord extends TActiveRecord
{
	const TABLE='tbt_rawat_jalan_caramsk';

	public $no_trans;
	public $keterangan;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>