<?php
/**
 * Auto generated by prado-cli.php on 2008-05-08 02:37:45.
 */
class SimpegPenghargaanRecord extends TActiveRecord
{
	const TABLE='tbd_simpeg_penghargaan';

	public $id;
	public $nip;
	public $nm_penghargaan;
	public $tgl_penghargaan;
	public $no_penghargaan;
	public $instansi;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>