<?php
/**
 * Auto generated by prado-cli.php on 2008-05-07 11:46:37.
 */
class SimpegLatihTeknisRecord extends TActiveRecord
{
	const TABLE='tbd_simpeg_pelatihan_teknis';

	public $id;
	public $nip;
	public $nm_pelatihan;
	public $thn_pelatihan;
	public $lama_pelatihan;
	public $penyelenggara;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>