<?php
/**
 * Auto generated by prado-cli.php on 2008-04-28 04:02:20.
 */
class SpareTimeInapRecord extends TActiveRecord
{
	const TABLE='tbm_sparetime_inap';

	public $id;
	public $jml_jam;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>