<?php
/**
 * Auto generated by prado-cli.php on 2008-04-04 12:34:16.
 */
class SpesialisRecord extends TActiveRecord
{
	const TABLE='tbm_spesialis';

	public $id;
	public $nama;
	public $id_klinik;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>