<?php
/**
 * Auto generated by prado-cli.php on 2008-05-23 06:21:35.
 */
class StokLainRecord extends TActiveRecord
{
	const TABLE='tbt_stok_lain';

	public $id;
	public $id_obat;
	public $id_harga;
	public $jumlah;
	public $sumber;
	public $tujuan;
	public $expired;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>