<?php
/**
 * Auto generated by prado-cli.php on 2008-05-16 12:58:54.
 */
class SubSumberObatRecord extends TActiveRecord
{
	const TABLE='tbm_sub_sumber_obat';

	public $id;
	public $id_sumber;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>