<?php
/**
 * Auto generated by prado-cli.php on 2008-05-16 12:58:40.
 */
class SumberObatRecord extends TActiveRecord
{
	const TABLE='tbm_sumber_obat';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>