<?php
/**
 * Auto generated by prado-cli.php on 2008-05-18 01:11:30.
 */
class TanahRecord extends TActiveRecord
{
	const TABLE='tbd_asset_tanah';

	public $id;
	public $alamat;
	public $luas;
	public $hrg_beli;
	public $tgl_beli;
	public $no_akte;
	public $tgl_akte;
	public $notaris;
	public $ket;
	public $jumlah;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>