<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:45.
 */
class TarifAdmKamarRecord extends TActiveRecord
{
	const TABLE='tbm_adm_harga';

	public $id_kls;
	public $adm;
	public $jsp;
	public $utk;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
