<?php
/**
 * Auto generated by prado-cli.php on 2008-05-14 05:27:45.
 */
class TarifPendaftaranRecord extends TActiveRecord
{
	const TABLE='tbm_tarif_pendaftaran';

	public $id;	
	public $id_klinik;
	public $shift;
	public $tarif;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>