<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class TarifAmbulanTungguRecord extends TActiveRecord
{
	const TABLE='tbm_ambulan_tunggu';

	public $id;
	public $tarif_jam_pertama;
	public $tarif_jam_berikutnya;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
