<?php
/**
 * Auto generated by prado-cli.php on 2008-06-02 05:12:55.
 */
class TindakanWajibRwtJlnRecord extends TActiveRecord
{
	const TABLE='tbt_tindakan_wajib_rwtjln';

	public $id;
	public $id_poli;
	public $id_tindakan;
	public $st;
	public $st_asuransi;
	public $dokter;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>