<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class UkuranFilmRecord extends TActiveRecord
{
	const TABLE= 'tbm_ukuran_film';

	public $id;
	public $nama;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>