<?php
/**
 * Auto generated by Kampre ~ ActiveRecordGen.php on 2009-06-17 07:30:52.
 */
class UnitInternalRecord extends TActiveRecord
{
	const TABLE='tbm_unit_internal';

	public $id;
	public $nama;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
