<?php
/**
 * Auto generated by prado-cli.php on 2008-04-03 07:41:12.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='tbd_user';

	public $username;
	public $password;
	public $real_name;
	public $no_hp;
	public $nip;
	public $role;
	public $allow;
	public $status;
	public $tgl_create;
	public $wkt_create;
	public $tgl_log;
	public $wkt_log;
	public $catatan;
	public $theme;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>